# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier = "douyin"
    name       = "Douyin"
    url        = "https://www.douyin.com/user/MS4wLjABAAAANWoZa71_aQ5dKb9flI-hNQz6I7RiJHEfuRqT1raXrr4"

    [social.params]
        icon = "brand-douyin"
        newtab = true

